#Configuracion de los contenedores de Docker para la aplicacion
services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SGU_user
    ports:
      - "3307:3306"
    networks:
      - sgu-net
    volumes:
      - sgu-volume:/var/lib/mysql

  frontend:
    image: client:1.0-sgu
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASE: /user
        API_PROTOCOL: https
    container_name: sgu-frontend
    ports:
      - "3080:80"
      - "3001:443"
    networks:
      - sgu-net
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - database

  backend:
    image: server:1.0-sgu
    build:
      context: ./server/server
    container_name: sgu-backend
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: SGU_user
      DB_USER: root
      DB_PASS: root
      SERVER_SSL_ENABLED: true
      SERVER_SSL_KEYSTORE: /etc/letsencrypt/live/localhost/keystore.p12
      SERVER_SSL_KEYSTORE_PASS: changeit
    ports:
      - "8081:8080"
    networks:
      - sgu-net
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - frontend

#CONFIGURACION DE LA RED Y VOLUMENES
networks:
  sgu-net:
    external: true

volumes:
  sgu-volume:
    external: true
  certbot-conf:
    external: true